- hosts: k8s_worker
  remote_user: ubuntu
  become: yes
  gather_facts: true
  vars:
    os_version: xUbuntu_22.04
    crio_version: 1.26
  roles:
    # - exp
    - network_setting
    # - containerd_install
    - crio_install
    - kubernetes_install
  tasks:
    - name: print ansible_host
      debug:
        msg:
          - "{{ ansible_host }}"
          - "{{ inventory_hostname }}"
          - "{{ ansible_distribution_major_version }}"
          - "{{ ansible_architecture }}"

