---

- name: install vxlan module
  # Flannel use VXLAN
  apt:
    name:
      - linux-modules-extra-raspi
    # notify:
    #   - reboot

- name: memory enabled
  # not idempotent
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: 'splash$'
    replace: 'splash cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  # notify:
  #   - reboot

- name: magic word
  shell: |
    echo '1' > /proc/sys/net/ipv4/ip_forward

- name: activate k8s.conf
  shell: sysctl --system

- name: inactivate swap
  # デフォルトで swap 領域は使わないようになってる気がする
  shell: swapoff -a

- name: install iptables
  apt:
    name:
      - iptables
      - arptables
      - ebtables
  when:
    - ansible_distribution_major_version == "22"

- name: activate legacy version
  shell: |
    update-alternatives --set iptables /usr/sbin/iptables-legacy
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
    update-alternatives --set arptables /usr/sbin/arptables-legacy
    update-alternatives --set ebtables /usr/sbin/ebtables-legacy
  when:
    - ansible_distribution_major_version == "22"

- name: prepare install kube
  apt:
    name:
      - apt-transport-https
      - curl

- name: download key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

- name: make Kubernetes deb
  copy:
    remote_src: no
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: apt update
  apt:
    update_cache: yes

- name: install kube
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl

- name: hold kube
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
