---

- name: add docker repository
  expect:
    command: |
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    responses:
      ".*Press [ENTER] to continue or Ctrl-c to cancel.$": "\n"